### ISSUE TITLE
[Flask API] Logout doesn't work

### ISSUE THREAD

**Issue by skohari** [app-generator/react-soft-ui-dashboard-pro#2]
On the PRO version: On starting up React FE and Flask API BE, it directly shows me as logged in; and on hitting 'Sign Out' in the top right corner, it doesn't sign me out. 
Are there any settings/configs that need to be changed to make the base version work? 
Do provide the steps, thank you.

**Comment by app-generator** [comment]
Hello @skohari 

Just tested the flow, all looks good. 

Please follow this `set up`: 

- Install and start the [Flask API](https://github.com/app-generator/api-server-flask) 
- Test the API using  POSTMAN (optional)
- Install modules and start the React API
  - `yarn` for modules
  - `yarn start` for development mode 
  - Access the UI using a new Browser window `incognito mode` (you might have old cookies) 

If still not working, please reply with the errors shown in the JS console.

**Comment by skohari** [comment]
Yup; worked on a full re-do and in incognito mode. Thank you.

**Comment by app-generator** [comment]
Anytime! 🚀
